pipeline {
    agent any

    environment {
        IMAGE_NAME    = "my-node-app"
        IMAGE_TAG     = "v1"
        CHART_PATH    = "helm/mychart"
        GIT_CRED_ID   = "github-creds"            // Change to your Jenkins Git credential ID
        DOCKER_CRED_ID = "dockerhub-creds"        // Change if your DockerHub credential ID is different
        KUBE_CRED_ID   = "kubeconfig-creds"       // Jenkins kubeconfig credential ID
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: "${GIT_CRED_ID}", url: 'https://github.com/avkhaladkar1991/k8s-node-express-mysql-api-deploy-via-helm.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:$IMAGE_TAG .'
            }
        }

        stage('Push Docker Image to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${DOCKER_CRED_ID}", usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_PASSWORD')]) {
                    sh '''
                        echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
                        docker tag $IMAGE_NAME:$IMAGE_TAG $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG
                        docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes using Helm') {
            steps {
                withCredentials([kubeconfigFile(credentialsId: "${KUBE_CRED_ID}", variable: 'KUBECONFIG')]) {
                    sh '''
                        helm upgrade --install $IMAGE_NAME $CHART_PATH \
                          --set image.repository=$DOCKERHUB_USERNAME/$IMAGE_NAME \
                          --set image.tag=$IMAGE_TAG
                    '''
                }
            }
        }
    }

    post {
        always {
            sh 'helm list'
        }
    }
}
