# Default values for api-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: your-dockerhub-username/my-node-app   # 👈 change this to your Docker Hub repo
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: LoadBalancer
  port: 3000                                        # Node.js default port

resources: {}
  # limits:
  #   cpu: 200m
  #   memory: 256Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

# =========================
# ✅ MySQL Configuration
# =========================
mysql:
  image:
    repository: bitnami/mysql
    tag: 8.0
  auth:
    database: api_db
    username: mysql-user
    existingSecret: api-db-pass                     # secret containing MySQL password
  primary:
    persistence:
      enabled: false                                # disable persistent volume for testing
  initdbScripts:
    1-create-table-users.sql: |-
      CREATE TABLE users (
        userID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        firstName VARCHAR(255),
        lastName VARCHAR(255),
        createdOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    2-add-dummy-users.sql: |-
      INSERT INTO users (firstName, lastName) VALUES ('Noam', 'Chomsky');
      INSERT INTO users (firstName, lastName) VALUES ('Elon', 'Musk');
      INSERT INTO users (firstName, lastName) VALUES ('Jeff', 'Bezos');
      INSERT INTO users (firstName, lastName) VALUES ('James', 'Watson');

# =========================
# ✅ Environment Variables
# =========================
env:
  - name: DB_HOST
    value: my-mysql.default.svc.cluster.local       # internal DNS of mysql service
  - name: DB_USER
    value: mysql-user
  - name: DB_NAME
    value: api_db
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: api-db-pass
        key: mysql-password
